// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Models;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(BonvoyageUsersDbContext))]
    [Migration("20240711053025_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackageWebService.Models.RefreshTokenClass", b =>
                {
                    b.Property<string>("RefreshTOken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RefreshTokenExpirationTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RefreshTOken");

                    b.ToTable("RefreshTokensClasses");
                });

            modelBuilder.Entity("UserService.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userID");

                    b.Property<string>("UserAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userAddress");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("userEmail");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("userName");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userPassword");

                    b.Property<long>("UserPhone")
                        .HasColumnType("bigint")
                        .HasColumnName("userPhone");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userRole");

                    b.HasKey("UserId")
                        .HasName("PK__Users__CB9A1CDF178C9F2C");

                    b.HasIndex(new[] { "UserName" }, "UQ__Users__66DCF95C8DD2FB74")
                        .IsUnique();

                    b.HasIndex(new[] { "UserEmail" }, "UQ__Users__D54ADF55540008AA")
                        .IsUnique();

                    b.HasIndex(new[] { "UserPhone" }, "UQ__Users__E19C969116561133")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
